name: copc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pdal>=2.6
  - python-pdal>=3.2
  - numpy
  - gdal
  - laszip
  # Optional but useful for inspecting outputs
  - lazperf
  - pip
 